server {
    listen 80;
    server_name stickstock.lol www.stickstock.lol;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name stickstock.lol www.stickstock.lol;

    ssl_certificate     /etc/letsencrypt/live/stickstock.lol/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/stickstock.lol/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    client_max_body_size 25m;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options    nosniff always;
    add_header X-Frame-Options           DENY always;
    add_header X-XSS-Protection          "1; mode=block" always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy
    "default-src 'self';      script-src 'self' 'unsafe-inline' 'unsafe-eval';      script-src-elem 'self' 'unsafe-inline' 'unsafe-eval';      style-src 'self' 'unsafe-inline';      style-src-attr 'unsafe-inline';      img-src 'self' data: blob:;      connect-src 'self' https://*.supabase.co wss://*.supabase.co;      frame-ancestors 'none';" always;

    location /api/ {
        proxy_pass         http://172.18.0.4:8080/api/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location /ws/ {
        proxy_pass         http://172.18.0.4:8080/ws/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host       $host;
    }

    location / {
        proxy_pass         http://172.18.0.2:3000;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
